### ISSUE TITLE
Make Logo Bigger

### ISSUE THREAD

**Issue by DeepNinja07x** [CodeChef-CIEM/CodeChef-CIEM.github.io#6]
Make the CodeChef-CIEM Chapter's Logo a little bigger only for mobile (max-width: 480px). Height and width can be 30% or depending upon the look

**Comment by aditya28sarin** [comment]
Hey, can you assign this issue to me, I am interested in working on this issue

**Comment by DeepNinja07x** [comment]
Yeah work on it
